# Outputs generated by main.tf
output "ssh_key_name" {
    description = "SSH Key for instance login"
    value = "${alicloud_key_pair.flowlog-example-ssh-key.key_file}"
}

output "user_login" {
    description = "Login name for ECS instance"
    value = "root"
}

# ECS instance private IP address
output "ecs_public_ip" {
    description = "ECS instance public IP"
    value = "${alicloud_instance.flowlog-example-ecs.public_ip}"
}

