#
# Outputs generated by main.tf
#
# These are needed to log into the ECS instance main.tf creates, as well
# as to set up ownCloud through the ownCloud web interface
#

output "ssh_key_name" {
  description = "SSH key for instance login (all instances)"
  value       = "${var.ssh_key_name}"
}

output "gitlab_url" {
  description = "GitLab URL"
  value       = "${alicloud_dns_record.gitlab-dns.host_record}.${alicloud_dns_record.gitlab-dns.name}"
}

output "sonar_url" {
  description = "SonarQube URL"
  value       = "${alicloud_dns_record.sonar-dns.host_record}.${alicloud_dns_record.sonar-dns.name}"
}
